[package]
name = "cc-client"
version = "0.1.0"
authors = ["jnowaczek <jnowaczek@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.13.1"
zip = "0.5.4"
base64 = "0.11.0"